[package]
name = "stats_alloc"
version = "0.1.0"
authors = ["Marcus Griep <mgriep@griep.us>"]
description = "An allocator wrapper that allows for instrumenting global allocators"
keywords = ["alloc", "instrument", "stats"]
exclude = [
    ".gitignore",
]
