sign-commit = true
upload-doc = true
tag-prefix = "v"
pre-release-commit-message = "Release {{version}} 🎉🎉"

[[pre-release-replacements]]
file="CHANGELOG.md"
search="Unreleased"
replace="{{version}}"

[[pre-release-replacements]]
file="CHANGELOG.md"
search="ReleaseDate"
replace="{{date}}"
